import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import { Map, AlertCircle, ChevronRight, Fingerprint, DollarSign, Layers, Target } from 'lucide-react';
import clsx from 'clsx';
import type { PlanSummary } from '@/types';

import { ANALYZER_V2_URL } from '@/lib/config';

const statusColors: Record<string, { bg: string; text: string }> = {
  draft: { bg: 'bg-gray-100', text: 'text-gray-700' },
  approved: { bg: 'bg-blue-100', text: 'text-blue-800' },
  executing: { bg: 'bg-amber-100', text: 'text-amber-800' },
  completed: { bg: 'bg-green-100', text: 'text-green-800' },
  failed: { bg: 'bg-red-100', text: 'text-red-800' },
};

function StatusBadge({ status }: { status: string }) {
  const colors = statusColors[status] || statusColors.draft;
  return (
    <span className={clsx('badge text-xs px-2 py-0.5', colors.bg, colors.text)}>
      {status}
    </span>
  );
}

function PlanCard({ plan }: { plan: PlanSummary }) {
  return (
    <Link
      href={`/plans/${plan.plan_id}`}
      className="card p-4 hover:shadow-md transition-shadow group"
    >
      <div className="flex items-start justify-between">
        <div className="flex-1 min-w-0">
          {/* Header: thinker name + status */}
          <div className="flex items-center gap-2 flex-wrap">
            <Map className="h-5 w-5 text-indigo-500 flex-shrink-0" />
            <h3 className="text-sm font-semibold text-gray-900 truncate">
              {plan.thinker_name}
            </h3>
            <StatusBadge status={plan.status} />
          </div>

          {/* Target work title */}
          <p className="mt-1 text-sm text-gray-600 line-clamp-2">
            {plan.target_work_title}
          </p>

          {/* Plan ID */}
          <p className="mt-1 text-xs text-gray-400 font-mono truncate">
            {plan.plan_id}
          </p>

          {/* Metadata row */}
          <div className="mt-3 flex flex-wrap items-center gap-2">
            {/* Phase count */}
            <span className="inline-flex items-center gap-1 text-xs text-gray-500">
              <Layers className="h-3.5 w-3.5" />
              {plan.phase_count} phases
            </span>

            {/* Cost estimate */}
            <span className="inline-flex items-center gap-1 text-xs text-gray-500">
              <DollarSign className="h-3.5 w-3.5" />
              ${(Number(plan.estimated_total_cost_usd) || 0).toFixed(2)}
            </span>

            {/* Depth profile */}
            {plan.estimated_depth_profile && (
              <span className="badge bg-purple-50 text-purple-700 text-xs">
                {plan.estimated_depth_profile}
              </span>
            )}
          </div>

          {/* Bottom badges */}
          <div className="mt-2 flex flex-wrap items-center gap-2">
            {plan.objective_key && (
              <span className="inline-flex items-center gap-1 badge bg-indigo-100 text-indigo-800 text-xs">
                <Target className="h-3 w-3" />
                {plan.objective_key}
              </span>
            )}
            {/* We check for decision trace in the summary based on a known signal:
                the list endpoint returns PlanSummary which doesn't have decision_trace,
                but we'll add a "Traced" badge on the detail page. For the list, we show
                workflow_key as a helpful reference. */}
            <span className="badge bg-gray-50 text-gray-600 text-xs">
              {plan.workflow_key}
            </span>
          </div>
        </div>
        <ChevronRight className="h-5 w-5 text-gray-400 group-hover:text-indigo-500 transition-colors flex-shrink-0 mt-1" />
      </div>
    </Link>
  );
}

export default function PlansPage() {
  const { data, isLoading, error } = useQuery({
    queryKey: ['plans'],
    queryFn: async () => {
      const res = await fetch(`${ANALYZER_V2_URL}/v1/orchestrator/plans`);
      if (!res.ok) throw new Error('Failed to fetch plans');
      return res.json() as Promise<PlanSummary[]>;
    },
  });

  if (error) {
    return (
      <div className="flex items-center justify-center h-64 text-red-600">
        <AlertCircle className="h-6 w-6 mr-2" />
        Failed to load plans
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Analysis Plans</h1>
        <p className="mt-1 text-gray-500">
          Adaptive pipeline plans generated by the orchestrator planner
        </p>
      </div>

      {isLoading && (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {[...Array(4)].map((_, i) => (
            <div key={i} className="card p-4 animate-pulse">
              <div className="h-4 bg-gray-200 rounded w-3/4" />
              <div className="h-3 bg-gray-200 rounded w-full mt-2" />
              <div className="h-3 bg-gray-200 rounded w-1/2 mt-4" />
            </div>
          ))}
        </div>
      )}

      {!isLoading && data && (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {(Array.isArray(data) ? data : []).map((plan: PlanSummary) => (
            <PlanCard key={plan.plan_id} plan={plan} />
          ))}
        </div>
      )}

      {!isLoading && data && (Array.isArray(data) ? data : []).length === 0 && (
        <div className="card p-12 text-center">
          <Map className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <p className="text-gray-500">No plans generated yet</p>
        </div>
      )}
    </div>
  );
}
